CREATE table product (
	productID BIGINT AUTO_INCREMENT PRIMARY KEY,
    userID BIGINT,
    userName VARCHAR (30),
    FOREIGN KEY (userID) REFERENCES usertable(userID),
    FOREIGN KEY (userName) REFERENCES usertable(userName),
    productName VARCHAR(30) NOT NULL,
    productPrice FLOAT NOT NULL,
    productQuantity BIGINT NOT NULL,
    productImage1 VARCHAR(500),
    productImage2 VARCHAR(500),
    productImage3 VARCHAR(500),
    productImage4 VARCHAR(500),
    productImage5 VARCHAR(500),
    productImage6 VARCHAR(500),
    productImage7 VARCHAR(500),
	productDescription VARCHAR(500) NOT NULL,
    productTag1 VARCHAR(30) NOT NULL,
    productTag2 VARCHAR(30),
    productTag3 VARCHAR(30),    
    productTag4 VARCHAR(30),
    productTag5 VARCHAR(30),
    productTag6 VARCHAR(30),
    productTag7 VARCHAR(30)
);